on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: [master]

name: Test on Windows
jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dguardpp_tests=ON && cmake --build . --config Debug"

      - name: Run Tests
        run: "D:\\a\\guardpp\\guardpp\\build\\Debug\\guardpp_test.exe D:\\a\\guardpp\\guardpp\\build\\Debug\\guardpp_test_exe.exe" # Hard-code path because windows...